version: "3.8"

services:
  tor:
    image: ghcr.io/yuki-js/anonymity-sandbox/tor:latest
    build: ../images/tor
    ports:
      - "0.0.0.0:59722:22" # You can do `ssh -p 59722 user@localhost` to connect to the container
    configs:
      - source: tor
        target: /etc/tor/torrc
        mode: 0444
    networks:
      int-tor-proxy:
      ext-tor:
    deploy:
      replicas: 1
    stop_grace_period: 1s

  workspace:
    image: ghcr.io/yuki-js/anonymity-sandbox/workspace:latest
    build: ../images/workspace
    environment:
      - DISPLAY
      - MOZ_ENABLE_WAYLAND
      - http_proxy=socks5://tor:9050
      - https_proxy=socks5://tor:9050
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /mnt/wslg/runtime-dir/wayland-0:/runtime/wayland-0:ro # WSLg bug that don't create the default socket
    networks:
      - int-tor-proxy
    depends_on:
      - tor
networks:
  int-tor-proxy:
    internal: true
  ext-tor:
    internal: false

configs:
  tor:
    file: ../configs/torrc
